# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIEaRS8ff9u43-Zz92vNLkMMFGMlU9-x
"""

#password generator
import random
import string
def generate_password(min_length , numbers=True , special_characters=True):
  letters = string.ascii_letters
  digits = string.digits
  special = string.punctuation

  characters = letters
  if numbers:
    characters += digits
  if special_characters:
    characters += special

  pwd = ""
  meets_criteria = False
  has_number = False
  has_special = False

  while not meets_criteria or len(pwd) < min_length:
    new_char = random.choice(characters)
    pwd += new_char
    if new_char in digits:
      has_number = True
    elif new_char in special:
      has_special = True

    meets_criteria = True
    if numbers:
       meets_criteria = meets_criteria and has_number
    if special_characters:
      meets_criteria = meets_criteria and has_special

  return pwd

min_length = int(input("Enter the minimum length :"))
has_number_input = input("Do you want to have numbers(y/n)?").lower()
has_special_input = input("Do you want to have special characters(y/n)?").lower()


has_number = True if has_number_input == 'y' else False
has_special = True if has_special_input == 'y' else False

def get_password_length(password):
  return len(password)

pwd = generate_password(min_length, has_number, has_special)
print("The generated password is:", pwd)

pwd = generate_password(10)
print(pwd)
print("password lenth :", get_password_length(pwd))